### ISSUE TITLE
Async the database connection using express-idempotency-mongo-adapter

### ISSUE THREAD

**Issue by bbbouvier** [VilledeMontreal/express-idempotency#25]
For of all thank you very much for this library which is really helpful, I am using it with the express-idempotency-mongo-adapter and it works perfectly.

Although I integrated it within some specific routes of my api located under a Google Cloud Function, and it create many extras connection to the database even though the specific routes are not called. 

How could review the idempotency service to create database connection, only when the actual routes using the idempotency service gets called ? 

Thanks in advance for your recommandations.

**Comment by joscelynjean** [comment]
Hi @rodneyrd ,

Thank you for your comment. It is really appreciated.

As for your issue, I think it is more related to the express idempotency mongo adapter itself than the express idempotency library. I will invite you to create the issue in the express-idempotency-mongo-adapter repository.

My understanding is that you want to avoid using the connection pool and instead, create the connection just-in-time, when it is required, is it correct?

In that case, I would use the delegate functionality instead of providing the standard mongo configuration. But the way the code is made, I think it keeps the connection, which is not ideal for your problem. I think I could bring an improvement before the end of the week if you open an issue.

Does it meet your expectation?

**Comment by bbbouvier** [comment]
Hi @joscelynjean, thank you very much for your reactivity.

> My understanding is that you want to avoid using the connection pool and instead, create the connection just-in-time, when it is required, is it correct?

Yes, it is exactly the result I'd like to get. I tried to play around with the useDelegation/delegate options, but couldn't get it working as expected.   

By the end of the week would be beyond my expectation :)

I am opening up the issue within the adapter itself: [link to the issue](https://github.com/VilledeMontreal/express-idempotency-mongo-adapter/issues/11)

**Comment by joscelynjean** [comment]
Thank you, I will close this one since it is handled in the appropriate repository.
